# Files for logging/debugging
Log:
  timefile: Timings.log
  logfile: C2Ray.log

# Input Files for the run (densities, redshift tables,...)
Input:
  redfile: redshifts.txt
  density_prefix: dens #../coarser_densities/dens

# Grid Parameters
Grid:
  mesh: [100,100,100]
  boxsize: 1

# Output parameters
Output:
  do_photonstatistics: 1
  photon_statistics_file_1: PhotonCounts.out
  photon_statistics_file_2: PhotonCounts2.out

# Material properties
Material:
  isothermal: 1
  initial_temperature: 1e4

# Time integration parameters
Time:
  number_timesteps: 10            # Number of timesteps between redshift slices
  number_outputs: 1               # Number of outputs between redshift slices

# Parameters for SED (BB)
SED:
  stellar_SED_type: 1
  # Effective temperature (K); if set to zero, the code will ask for SED parameters
  bb_Teff: 5.0e4
  # Number of ionizing photons / second (reference)
  bb_S_star: 1e48_dp
  # nominal minimum and maximum frequency for BB source
  bb_MinFreq: ion_freq_HI
  bb_MaxFreq: ion_freq_HeII * 10.00_dp
  # nominal power law index (for photon number)
  pl_index: 3.0_dp
  # Number of ionizing photons / second (reference)
  pl_S_star: 1e48_dp
  # nominal minimum and maximum frequency for power law source
  pl_MinFreq: ion_freq_HI
  pl_MaxFreq: ion_freq_HeII! * 100.00_dp
  # nominal Eddington efficiency
  EddLeff_nominal: 1.0_dp
  # nominal black hole mass for Eddington luminosity (M0)
  mass_nominal: 1.0e6_dp
  # Eddington luminosity per mass_nominal solar mass (erg/s)
  EddLum: 1.38e38*mass_nominal
  # Use an X-ray SED as well? This is not yet implemented so should be false.
  use_xray_SED: 0
  # Source properties: X-ray photons per baryon. Mesinger et al. (2012) use
  # 0.02 as their nominal value. Note that this depends on your integration
  # limits. Mesinger et al. use 300 eV as lowest energy.
  xray_phot_per_atom : 0.02